name: DEPLOY

on:
  schedule:
    - cron:  '0 0 */7 * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Gigalixir and login
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install gigalixir
          gigalixir login -e "$GIGALIXIR_EMAIL" -p "$GIGALIXIR_PASSWORD" --yes
        env:
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
      - name: Commit
        run: |
          git config --global user.email "jakop@pm.me"
          git config --global user.name "Jakob Pupke"
          git clone "$GIGALIXIR_REMOTE" anfrage && cd anfrage
          git commit --allow-empty -m "Force deploy"
          git push origin master
        env:
          GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP }}
          GIGALIXIR_REMOTE: ${{ secrets.GIGALIXIR_REMOTE }}
