name: DEPLOY

on:
  schedule:
    - cron:  '0 0 */7 * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Commit
        run: |
          git config --global user.email "jakop@pm.me"
          git config --global user.name "Jakob Pupke"
          git clone "$GIGALIXIR_REMOTE" anfrage && cd anfrage
          git commit --allow-empty -m "Force deploy"
          git push origin master
        env:
          GIGALIXIR_REMOTE: ${{ secrets.GIGALIXIR_REMOTE }}
