name: DEPLOY

on:
  schedule:
    - cron:  '0 0 */7 * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Gigalixir and login
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install gigalixir --user
          gigalixir login -e "$GIGALIXIR_EMAIL" -p "$GIGALIXIR_PASSWORD"
          echo "$HOME/runner/.local/bin" >> $GITHUB_PATH
      - name: Commit
        run: |
          git config --global user.email "jakop@pm.me"
          git config --global user.name "Jakob Pupke"
          gigalixir git:remote "$GIGALIXIR_APP"
          git commit --allow-empty -m "Force deploy"
          git push gigalixir master
        env:
          GIGALIXIR_REMOTE: ${{ secrets.GIGALIXIR_REMOTE }}
