name: DEPLOY

on:
  schedule:
    - cron:  '0 0 */7 * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit
        run: |
          git remote add gigalixir "$GIGALIXIR_REMOTE"
          git commit --allow-empty -m "Force deploy"
          git push gigalixir master
        env:
          GIGALIXIR_REMOTE: ${{ secrets.GIGALIXIR_REMOTE }}
